//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Entidades;
    
    public partial class DBProyectoPlantillaMVCFrameworkEntities : DbContext
    {
        public DBProyectoPlantillaMVCFrameworkEntities()
            : base("name=DBProyectoPlantillaMVCFrameworkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cat_Materias> Cat_Materias { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Alumnos> tbl_Alumnos { get; set; }
        public virtual DbSet<tbl_Especialidades> tbl_Especialidades { get; set; }
        public virtual DbSet<tbl_IdMateria_IdAlumno_NN> tbl_IdMateria_IdAlumno_NN { get; set; }
    }
}
