//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_IdMateria_IdAlumno_NN
    {
        public int Id { get; set; }
        public int IdMateria { get; set; }
        public int IdAlumno { get; set; }
    
        public virtual Cat_Materias Cat_Materias { get; set; }
        public virtual tbl_Alumnos tbl_Alumnos { get; set; }
    }
}
